export const PortfolioPages = [
  {
    "id": "kotedzh-u-styli-loft",
    "year": 2011,
    "title": "Котедж у стилі лофт",
    "image": "/img/portfolio/cards/kottedzh-v-stile-loft.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Мікроцемент та декоративне оздоблення", "Ремонт бетону та залізобетону"],
    "body": "Об'єкт – котедж у стилі лофт.",
    "descr": [
      "Замовник попросив підлогу котеджу виконати бетонними за технологією топінгу. Ми із завданням справилися чудово. Замовник був у захваті. Йому настільки сподобалася ідея використання бетону в інтер'єрі, що він попросив відлити з бетону кухонну стільницю та раковину у ванній кімнаті.",
      "Робота була для нас новою та нестандартною. Особливу увагу ми звернули на якість виготовлення опалубки (практично машинобудівна точність) та склад та пропорцію бетонної суміші. З цим завданням ми також впоралися відмінно. Ухили в раковині вийшли ідеально! Вода стікає до останньої краплі!",
      "Пізніше на виставці у Мюнхені на одному зі стендів наш директор Сергій Миколайович Стародубов розмовляв із німцем, чий бізнес – це виготовлення бетонних елементів інтер'єру. Директор похвалився своїм проектом. Німець із недовірою подивився фотографії та сказав, що для виходу на такий рівень йому знадобилося 10 років. А у нас це вийшло з першого разу! Ну що ж, новачкам щастить =)"
    ],
    "images": [
      '/img/portfolio/1999/kotedzh-u-styli-loft.jpg'
    ]
  },
  {
    "id": "stavok-u-pryvatnomu-kotedzhi",
    "year": 2011,
    "title": "Ставок у приватному котеджі",
    "image": "/img/portfolio/cards/stavok-u-pryvatnomu-kotedzhi.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Гідроізоляція"],
    "body": "Ми були третіми, хто «лікує» цей невеликий, але дорогий серцю господині, ставок.",
    "descr": [
      "Спочатку була дорога епоксидна мастика. Але вона «чомусь» відшарувалася від основи. Потім була товста плівка. Але вона почала протікати на стику-вигині.",
      "Ура, відбулося! Тепер ми можемо наносити гідроізоляцію того кольору, що хоче замовник! З барвниками для мікроцементу Деко Колор (ISOMAT, Греція) це стало можливо!",
      "В даному випадку замовниця захотіла ніжно-зелена. Будь ласка!"
    ],
    "images": [
      "/img/portfolio/1999/stavok-u-pryvatnomu-kotedzhi-1.jpg",
      "/img/portfolio/1999/stavok-u-pryvatnomu-kotedzhi-2.jpg"
    ]
  },
  {
    "id": "remont-ruberoydnoyi-pokrivli",
    "year": 2011,
    "title": "Ремонт руберойдної покрівлі",
    "image": "/img/portfolio/cards/remont-ruberoydnoyi-pokrivli.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Гідроізоляція", "Посилення вуглецевими полотнами"],
    "body": "",
    "descr": [
      ""
    ],
    "images": [
      "/img/portfolio/1999/remont-ruberoydnoyi-pokrivli-1.jpg",
      "/img/portfolio/1999/remont-ruberoydnoyi-pokrivli-2.jpg",
      "/img/portfolio/1999/remont-ruberoydnoyi-pokrivli-3.jpg",
      "/img/portfolio/1999/remont-ruberoydnoyi-pokrivli-4.jpg",
      "/img/portfolio/1999/remont-ruberoydnoyi-pokrivli-5.jpg",
      "/img/portfolio/1999/remont-ruberoydnoyi-pokrivli-6.jpg",
      "/img/portfolio/1999/remont-ruberoydnoyi-pokrivli-7.jpg",
      "/img/portfolio/1999/remont-ruberoydnoyi-pokrivli-8.jpg",
      "/img/portfolio/1999/remont-ruberoydnoyi-pokrivli-9.jpg",
      "/img/portfolio/1999/remont-ruberoydnoyi-pokrivli-10.jpg",
      "/img/portfolio/1999/remont-ruberoydnoyi-pokrivli-11.jpg",
      "/img/portfolio/1999/remont-ruberoydnoyi-pokrivli-12.jpg",
      "/img/portfolio/1999/remont-ruberoydnoyi-pokrivli-13.jpg",
      "/img/portfolio/1999/remont-ruberoydnoyi-pokrivli-14.jpg",
      "/img/portfolio/1999/remont-ruberoydnoyi-pokrivli-15.jpg",
      "/img/portfolio/1999/remont-ruberoydnoyi-pokrivli-16.jpg",
      "/img/portfolio/1999/remont-ruberoydnoyi-pokrivli-17.jpg",
    ]
  },
  // {
  //   "id": "",
  //   "year": "1999-2009",
  //   "title": "",
  //   "image": "/img/portfolio/cards/",
  //   "place": "м.Харків, Україна",
  //   "technologies": ["Гідроізоляція"],
  //   "body": "",
  //   "descr": [
  //     "",
  //     "",
  //     ""
  //   ],
  //   "images": [
  //     "/img/portfolio/1999/jpg",
  //   ]
  // },
  // {
  //   "id": "zavod-blyk-rekonstruktsiya",
  //   "year": "1999-2009",
  //   "title": "Завод Блік-реконструкція",
  //   "image": "/img/portfolio/cards/",
  //   "place": "м.Харків, Україна",
  //   "technologies": ["Гідроізоляція"],
  //   "body": "",
  //   "descr": [
  //     "",
  //     "",
  //     ""
  //   ],
  //   "images": [
  //     "/img/portfolio/1999/zavod-blyk-rekonstruktsiya/zavod-blyk-rekonstruktsiya-.jpg",
  //   ]
  // },
  {
    "id": "hidroizolyatsiya-pidval-zavod-rohan",
    "year": "1999-2009",
    "title": "Гідроізоляція підвалу заводу РОГАНЬ",
    "image": "/img/portfolio/cards/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Гідроізоляція"],
    "body": "",
    "descr": [
      "",
      "",
      ""
    ],
    "images": [
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-1.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-2.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-3.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-4.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-5.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-6.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-7.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-8.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-9.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-10.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-11.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-12.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-13.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-14.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-15.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-16.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-17.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-18.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-19.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-20.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-21.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-22.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-23.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-24.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-25.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-26.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-27.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-28.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-29.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-30.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-31.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-32.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-33.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-34.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-35.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-pidval-zavod-rohan/hidroizolyatsiya-pidval-zavod-rohan-36.jpg",
    ]
  },
  {
    "id": "hidroizolyatsiya-balkonnoho-navisu",
    "year": "1999-2009",
    "title": "Гідроізоляція балконного навісу",
    "image": "/img/portfolio/cards/1999/hidroizolyatsiya-balkonnoho-navisu/hidroizolyatsiya-balkonnoho-navisu.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Гідроізоляція"],
    "body": "",
    "descr": [
      "",
      "",
      ""
    ],
    "images": [
      "/img/portfolio/1999/hidroizolyatsiya-balkonnoho-navisu/hidroizolyatsiya-balkonnoho-navisu-1.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-balkonnoho-navisu/hidroizolyatsiya-balkonnoho-navisu-2.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-balkonnoho-navisu/hidroizolyatsiya-balkonnoho-navisu-3.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-balkonnoho-navisu/hidroizolyatsiya-balkonnoho-navisu-4.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-balkonnoho-navisu/hidroizolyatsiya-balkonnoho-navisu-5.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-balkonnoho-navisu/hidroizolyatsiya-balkonnoho-navisu-6.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-balkonnoho-navisu/hidroizolyatsiya-balkonnoho-navisu-7.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-balkonnoho-navisu/hidroizolyatsiya-balkonnoho-navisu-8.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-balkonnoho-navisu/hidroizolyatsiya-balkonnoho-navisu-9.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-balkonnoho-navisu/hidroizolyatsiya-balkonnoho-navisu-10.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-balkonnoho-navisu/hidroizolyatsiya-balkonnoho-navisu-11.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-balkonnoho-navisu/hidroizolyatsiya-balkonnoho-navisu-12.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-balkonnoho-navisu/hidroizolyatsiya-balkonnoho-navisu-13.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-balkonnoho-navisu/hidroizolyatsiya-balkonnoho-navisu-14.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-balkonnoho-navisu/hidroizolyatsiya-balkonnoho-navisu-15.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-balkonnoho-navisu/hidroizolyatsiya-balkonnoho-navisu-16.jpg",
      "/img/portfolio/1999/hidroizolyatsiya-balkonnoho-navisu/hidroizolyatsiya-balkonnoho-navisu-17.jpg",
    ]
  },
  {
    "id": "andkhoy-budivelna-kompaniya",
    "year": "1999-2009",
    "title": "Андхой - будівельна компанія",
    "image": "/img/portfolio/cards/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Гідроізоляція"],
    "body": "Нанесення на асфальт зразка поліуретанового покриття Гіпердесмо",
    "descr": [
      "",
      "",
      ""
    ],
    "images": [
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-1.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-2.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-3.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-4.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-5.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-6.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-7.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-8.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-9.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-10.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-11.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-12.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-13.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-14.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-15.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-16.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-17.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-18.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-19.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-20.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-21.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-22.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-23.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-24.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-25.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-26.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-27.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-28.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-29.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-30.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-31.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-32.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-33.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-34.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-35.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-36.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-37.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-38.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-39.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-40.jpg",
      "/img/portfolio/1999/andkhoy-budivelna-kompaniya/andkhoy-budivelna-kompaniya-41.jpg",
    ]
  },
  {
    "id": "natsionalna-akademiya-pravovykh-nauk",
    "year": "1999-2009",
    "title": "Національна академія правових наук",
    "image": "/img/portfolio/cards/1999/natsionalna-akademiya-pravovykh-nauk/natsionalna-akademiya-pravovykh-nauk.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Гідроізоляція"],
    "body": "",
    "descr": [
      "",
      "",
      ""
    ],
    "images": [
      "/img/portfolio/1999/natsionalna-akademiya-pravovykh-nauk/natsionalna-akademiya-pravovykh-nauk-1.jpg",
      "/img/portfolio/1999/natsionalna-akademiya-pravovykh-nauk/natsionalna-akademiya-pravovykh-nauk-2.jpg",
      "/img/portfolio/1999/natsionalna-akademiya-pravovykh-nauk/natsionalna-akademiya-pravovykh-nauk-3.jpg",
      "/img/portfolio/1999/natsionalna-akademiya-pravovykh-nauk/natsionalna-akademiya-pravovykh-nauk-4.jpg",
      "/img/portfolio/1999/natsionalna-akademiya-pravovykh-nauk/natsionalna-akademiya-pravovykh-nauk-5.jpg",
      "/img/portfolio/1999/natsionalna-akademiya-pravovykh-nauk/natsionalna-akademiya-pravovykh-nauk-6.jpg",
      "/img/portfolio/1999/natsionalna-akademiya-pravovykh-nauk/natsionalna-akademiya-pravovykh-nauk-7.jpg",
      "/img/portfolio/1999/natsionalna-akademiya-pravovykh-nauk/natsionalna-akademiya-pravovykh-nauk-8.jpg",
      "/img/portfolio/1999/natsionalna-akademiya-pravovykh-nauk/natsionalna-akademiya-pravovykh-nauk-9.jpg",
      "/img/portfolio/1999/natsionalna-akademiya-pravovykh-nauk/natsionalna-akademiya-pravovykh-nauk-10.jpg",
      "/img/portfolio/1999/natsionalna-akademiya-pravovykh-nauk/natsionalna-akademiya-pravovykh-nauk-11.jpg",
      "/img/portfolio/1999/natsionalna-akademiya-pravovykh-nauk/natsionalna-akademiya-pravovykh-nauk-12.jpg",
      "/img/portfolio/1999/natsionalna-akademiya-pravovykh-nauk/natsionalna-akademiya-pravovykh-nauk-13.jpg",
      "/img/portfolio/1999/natsionalna-akademiya-pravovykh-nauk/natsionalna-akademiya-pravovykh-nauk-14.jpg",
      "/img/portfolio/1999/natsionalna-akademiya-pravovykh-nauk/natsionalna-akademiya-pravovykh-nauk-15.jpg",
      "/img/portfolio/1999/natsionalna-akademiya-pravovykh-nauk/natsionalna-akademiya-pravovykh-nauk-16.jpg",
      "/img/portfolio/1999/natsionalna-akademiya-pravovykh-nauk/natsionalna-akademiya-pravovykh-nauk-17.jpg",
    ]
  },
  {
    "id": "veza-ukrayina",
    "year": "1999-2009",
    "title": "Веза-Україна ",
    "image": "/img/portfolio/cards/1999/veza-ukrayina/veza-ukrayina.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Промислові та декоративні підлоги"],
    "body": "Ремонт бетонних підлог",
    "descr": [
      "",
      "",
      ""
    ],
    "images": [
      "/img/portfolio/1999/veza-ukrayina/veza-ukrayina-1.jpg",
      "/img/portfolio/1999/veza-ukrayina/veza-ukrayina-2.jpg",
      "/img/portfolio/1999/veza-ukrayina/veza-ukrayina-3.jpg",
      "/img/portfolio/1999/veza-ukrayina/veza-ukrayina-4.jpg",
      "/img/portfolio/1999/veza-ukrayina/veza-ukrayina-5.jpg",
      "/img/portfolio/1999/veza-ukrayina/veza-ukrayina-6.jpg",
      "/img/portfolio/1999/veza-ukrayina/veza-ukrayina-7.jpg",
      "/img/portfolio/1999/veza-ukrayina/veza-ukrayina-8.jpg",
      "/img/portfolio/1999/veza-ukrayina/veza-ukrayina-9.jpg",
      "/img/portfolio/1999/veza-ukrayina/veza-ukrayina-10.jpg",
      "/img/portfolio/1999/veza-ukrayina/veza-ukrayina-11.jpg",
      "/img/portfolio/1999/veza-ukrayina/veza-ukrayina-12.jpg",
      "/img/portfolio/1999/veza-ukrayina/veza-ukrayina-13.jpg",
      "/img/portfolio/1999/veza-ukrayina/veza-ukrayina-14.jpg",
      "/img/portfolio/1999/veza-ukrayina/veza-ukrayina-15.jpg",
      "/img/portfolio/1999/veza-ukrayina/veza-ukrayina-16.jpg",
      "/img/portfolio/1999/veza-ukrayina/veza-ukrayina-17.jpg",
      "/img/portfolio/1999/veza-ukrayina/veza-ukrayina-18.jpg",
    ]
  },
  {
    "id": "kharkivska-khoralna-synahoha-2003",
    "year": 2003,
    "title": "Харьківська хоральна сінагога",
    "image": "/img/portfolio/cards/harkivska-horalnaya-sinagoga.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Торкетування", "Ремонт бетону та залізобетону", "Очистка, реставрація та захист фасадів", "Склеювання тріщин", "Гідроізоляція"],
    "body": "",
    "descr": [
      ""
    ],
    "images": [
      "/img/portfolio/1999/.jpg"
    ]
  },
  {
    "id": "hidroizolyatsiya-kuli",
    "year": 2010,
    "title": "Гідроізоляція кулі",
    "image": "/img/portfolio/cards/gidroizolyacziya-shara-hire-harkov.jpg",
    "place": "ХНУРЕ (м. Харків), Україна",
    "technologies": ["Гідроізоляція"],
    "body": "Усі, хто проїжджає проспектом Науки в районі метро «Наукова», піднявши голову над вулицею Серпової, можуть побачити ось таку кулю.",
    "descr": [
      "У 2010 році ми його обробили спеціальними поліуретановими фарбами.",
      "Усі, хто проїжджає повз, з того часу можуть оцінити, чи впоралися ми з цим завданням? =)",
    ],
    "images": [
      "/img/portfolio/2010/hidroizolyatsiya-kuli.jpg"
    ]
  },
  {
    "id": "khram-svyato-boryso-hlibskoho-zhinochoho-monastyrya",
    "year": 2010,
    "title": "Храм Свято-Борисо-Глібського жіночого монастиря",
    "image": "/img/portfolio/cards/holovnyy-khram-svyato-boryso-hlibskoho-zhinochoho-monastyrya.jpg",
    "place": "с. Водяне, Україна",
    "technologies": ["Гідроізоляція", "Утеплення та модернізація", "Ремонт бетону та залізобетону"],
    "body": "Влаштування бетонної підлоги у головному храмі Свято-Борисо-Глібського жіночого монастиря у селищі Водяне Харківської області.",
    "descr": [
      ""
    ],
    "images": [
      "/img/portfolio/2010/khram-svyato-boryso-hlibskoho-zhinochoho-monastyrya-1.jpg",
      "/img/portfolio/2010/khram-svyato-boryso-hlibskoho-zhinochoho-monastyrya-2.jpg",
      "/img/portfolio/2010/khram-svyato-boryso-hlibskoho-zhinochoho-monastyrya-3.jpg",
      "/img/portfolio/2010/khram-svyato-boryso-hlibskoho-zhinochoho-monastyrya-4.jpg",
      "/img/portfolio/2010/khram-svyato-boryso-hlibskoho-zhinochoho-monastyrya-5.jpg",
      "/img/portfolio/2010/khram-svyato-boryso-hlibskoho-zhinochoho-monastyrya-6.jpg",
      "/img/portfolio/2010/khram-svyato-boryso-hlibskoho-zhinochoho-monastyrya-7.jpg",
      "/img/portfolio/2010/khram-svyato-boryso-hlibskoho-zhinochoho-monastyrya-8.jpg",
    ]
  },
  {
    "id": "kupyanskyy-molochnokonservnyy-kombinat",
    "year": 2010,
    "title": "Куп'янський молочноконсервний комбінат",
    "image": "/img/portfolio/cards/kupyanskyy-molochnokonservnyy-kombinat.jpg",
    "place": "м. Куп'янськ, Україна",
    "technologies": ["Ремонт бетону та залізобетону", "Гідроізоляція"],
    "body": "Відома торгова марка 'Заріччя'.",
    "descr": [
      "Найсмачніші кисло-молочні продукти!",
      "Складність полягала в тому, що доводилося одночасно враховувати кілька факторів. По-перше, необхідно забезпечити гідроізоляцію станції від рідин, що зливаються до неї. По-друге, рідини зливаються після промивання чанів, тобто. ми маємо справу з агресивною молочною кислотою. По-третє, станція знаходиться у землі та не виконана зовнішня гідроізоляція. Нанесене нами покриття має витримувати ще й тиск води зовні на відрив. Ну і на закуску, бетон цієї станції був залитий багато років тому, дуже неякісно і простояв багато років просто неба.",
      "Впоратися з поставленими завданнями допомогла система матеріалів фірми Remmers (Німеччина), авторизованими представниками якої ми є."
    ],
    "images": [
      "/img/portfolio/2010/kupyanskyy-molochnokonservnyy-kombinat-1.jpg",
      "/img/portfolio/2010/kupyanskyy-molochnokonservnyy-kombinat-2.jpg",
      "/img/portfolio/2010/kupyanskyy-molochnokonservnyy-kombinat-3.jpg",
      "/img/portfolio/2010/kupyanskyy-molochnokonservnyy-kombinat-4.jpg",
      "/img/portfolio/2010/kupyanskyy-molochnokonservnyy-kombinat-5.jpg",
      "/img/portfolio/2010/kupyanskyy-molochnokonservnyy-kombinat-6.jpg",
      "/img/portfolio/2010/kupyanskyy-molochnokonservnyy-kombinat-7.jpg",
      "/img/portfolio/2010/kupyanskyy-molochnokonservnyy-kombinat-8.jpg",
      "/img/portfolio/2010/kupyanskyy-molochnokonservnyy-kombinat-9.jpg",
    ]
  },
  {
    "id": "mist-pr-t-heroyiv-kharkova",
    "year": 2010,
    "title": "Міст пр-т Героїв Харкова",
    "image": "/img/portfolio/cards/mist-pr-t-heroyiv-kharkov.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Ремонт бетону та залізобетону", "Склеювання тріщин", "Піскоструминне очищення"],
    "body": "Реконструкція мосту та його піскоструминне очищення.",
    "descr": [
      ""
    ],
    "images": [
      "/img/portfolio/2010/mist-pr-t-heroyiv-kharkova-1.jpg",
      "/img/portfolio/2010/mist-pr-t-heroyiv-kharkova-2.jpg",
      "/img/portfolio/2010/mist-pr-t-heroyiv-kharkova-3.jpg",
      "/img/portfolio/2010/mist-pr-t-heroyiv-kharkova-4.jpg",
      "/img/portfolio/2010/mist-pr-t-heroyiv-kharkova-5.jpg",
      "/img/portfolio/2010/mist-pr-t-heroyiv-kharkova-6.jpg",
      "/img/portfolio/2010/mist-pr-t-heroyiv-kharkova-7.jpg",
      "/img/portfolio/2010/mist-pr-t-heroyiv-kharkova-8.jpg",
      "/img/portfolio/2010/mist-pr-t-heroyiv-kharkova-9.jpg",
      "/img/portfolio/2010/mist-pr-t-heroyiv-kharkova-10.jpg",
      "/img/portfolio/2010/mist-pr-t-heroyiv-kharkova-11.jpg",
      "/img/portfolio/2010/mist-pr-t-heroyiv-kharkova-12.jpg",
      "/img/portfolio/2010/mist-pr-t-heroyiv-kharkova-13.jpg",
      "/img/portfolio/2010/mist-pr-t-heroyiv-kharkova-14.jpg",
    ]
  },
  {
    "id": "piskostrumynna-ochystka-pidvalu-restoranu",
    "year": 2010,
    "title": "Піскоструминна очистка підвалу ресторану",
    "image": "/img/portfolio/cards/piskostrumynka-pidvalu-restoranu.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Піскоструминне очищення"],
    "body": "Є звичайні піскоструминні установки, в яких пісок вилітає «в лоб» і вигризає в цеглині ​​вибоїни.",
    "descr": [
      "А ми застосовуємо піскоструминну установку фірми «ROTEK» (Німеччина), в якій пісок закручується по спіралі і підлітає до поверхні «дотичної». Цим забезпечується щадне очищення поверхні. Ми можемо з газети зняти літери, не пошкодивши папір!"
    ],
    "images": [
      "/img/portfolio/2010/piskostrumynna-ochystka-pidvalu-restoranu-1.jpg",
      "/img/portfolio/2010/piskostrumynna-ochystka-pidvalu-restoranu-2.jpg",
      "/img/portfolio/2010/piskostrumynna-ochystka-pidvalu-restoranu-3.jpg",
      "/img/portfolio/2010/piskostrumynna-ochystka-pidvalu-restoranu-4.jpg",
      "/img/portfolio/2010/piskostrumynna-ochystka-pidvalu-restoranu-5.jpg",
      "/img/portfolio/2010/piskostrumynna-ochystka-pidvalu-restoranu-6.jpg",
      "/img/portfolio/2010/piskostrumynna-ochystka-pidvalu-restoranu-7.jpg",
    ]
  },
  {
    "id": "restavratsiya-derevyny-vkhidnoyi-hrupy",
    "year": 2010,
    "title": "Реставрація деревини вхідної групи",
    "image": "/img/portfolio/cards/restavratsiya-derevyny-vkhidnoyi-hrupy.jpg",
    "place": "ХНУРЕ (м. Харків), Україна",
    "technologies": ["Очистка, реставрація та захист фасадів"],
    "body": "Чого не зробиш для шановних Замовників",
    "descr": [
      "Навіть перекваліфікуєшся на столяри))",
      "Реставрація деревини вхідної групи, ХНУРЕ, Харків"
    ],
    "images": [
      "/img/portfolio/2010/restavratsiya-derevyny-vkhidnoyi-hrupy-1.jpg",
      "/img/portfolio/2010/restavratsiya-derevyny-vkhidnoyi-hrupy-2.jpg",
      "/img/portfolio/2010/restavratsiya-derevyny-vkhidnoyi-hrupy-3.jpg",
    ]
  },
  {
    "id": "restavratsiya-budivli",
    "year": 2010,
    "title": "Реставрація будівлі",
    "image": "/img/portfolio/cards/restavratsiya-budivli-kharkiv.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Гідроізоляція", "Торкетування", "Очистка, реставрація та захист фасадів", "Піскоструминне очищення"],
    "body": "Будівля на вул. Дарвіна – перлина нашої колекції.",
    "descr": [
      "Пам'ятка архітектури.",
      "Повний комплекс робіт: підсилення фундаментів, гідроізоляція підвалу, заміна перекриттів, гідроізоляція терас. І знову-таки перлина наших технологій - реставрація фасаду з червоної цеглини - щадна піскоструминка, відновлення втраченої цегли, заповнення швів спеціальним шовним розчином, гідрофобне просочення.",
      "Наразі майже всі весілля Харкова влаштовують фотосесію біля цієї будівлі! =)",
    ],
    "images": [
      "/img/portfolio/2010/restavratsiya-budivli-1.jpg",
      "/img/portfolio/2010/restavratsiya-budivli-2.jpg",
      "/img/portfolio/2010/restavratsiya-budivli-3.jpg",
      "/img/portfolio/2010/restavratsiya-budivli-4.jpg",
      "/img/portfolio/2010/restavratsiya-budivli-5.jpg",
      "/img/portfolio/2010/restavratsiya-budivli-6.jpg",
      "/img/portfolio/2010/restavratsiya-budivli-7.jpg",
      "/img/portfolio/2010/restavratsiya-budivli-8.jpg",
      "/img/portfolio/2010/restavratsiya-budivli-9.jpg",
      "/img/portfolio/2010/restavratsiya-budivli-10.jpg",
      "/img/portfolio/2010/restavratsiya-budivli-11.jpg",
      "/img/portfolio/2010/restavratsiya-budivli-12.jpg",
      "/img/portfolio/2010/restavratsiya-budivli-13.jpg",
      "/img/portfolio/2010/restavratsiya-budivli-14.jpg",
      "/img/portfolio/2010/restavratsiya-budivli-15.jpg",
      "/img/portfolio/2010/restavratsiya-budivli-16.jpg",
      "/img/portfolio/2010/restavratsiya-budivli-17.jpg",
      "/img/portfolio/2010/restavratsiya-budivli-18.jpg",
    ]
  },
  {
    "id": "restavratsiya-tsehly-biblioteka-ntu-khpi",
    "year": 2010,
    "title": "Реставрація цегли, бібліотека НТУ 'ХПІ'",
    "image": "/img/portfolio/cards/restavratsiya-tsehly-biblioteka-ntu-khpi.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Очистка, реставрація та захист фасадів"],
    "body": "Іноді доводиться реставрувати і нову цеглу.Будівля бібліотеки НТУ 'ХПІ'.",
    "descr": [
      "Об'єкт виконано у 2010 році. Запрошуємо всіх бажаючих здійснити до нього екскурсію, насолодитися архітектурою, і, заради інтересу, спробувати вгадати, яка цегла реставрувалася, а яка ні)."
    ],
    "images": [
      "/img/portfolio/2010/restavratsiya-tsehly-biblioteka-ntu-khpi-1.jpg",
      "/img/portfolio/2010/restavratsiya-tsehly-biblioteka-ntu-khpi-2.jpg",
      "/img/portfolio/2010/restavratsiya-tsehly-biblioteka-ntu-khpi-3.jpg",
      "/img/portfolio/2010/restavratsiya-tsehly-biblioteka-ntu-khpi-4.jpg",
      "/img/portfolio/2010/restavratsiya-tsehly-biblioteka-ntu-khpi-5.jpg",
      "/img/portfolio/2010/restavratsiya-tsehly-biblioteka-ntu-khpi-6.jpg",
      "/img/portfolio/2010/restavratsiya-tsehly-biblioteka-ntu-khpi-7.jpg",
      "/img/portfolio/2010/restavratsiya-tsehly-biblioteka-ntu-khpi-8.jpg",
      "/img/portfolio/2010/restavratsiya-tsehly-biblioteka-ntu-khpi-9.jpg",
      "/img/portfolio/2010/restavratsiya-tsehly-biblioteka-ntu-khpi-10.jpg",
    ]
  },
  {
    "id": "restavratsiyastaroyi-tsehly",
    "year": 2010,
    "title": "Реставрація старої цегли",
    "image": "/img/portfolio/cards/restavratsiya-staroyi-tsehly-turahentstvo.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Очистка, реставрація та захист фасадів"],
    "body": "Шарівка - білокам'яна споруда кінця XIX століття неоготичного стилю, колишня поміщицька садиба.",
    "descr": [
      "Розташована у смт Шарівка Богодухівського району Харківської області на березі річки Мерчик.",
      "Садиба заснована у селі Шарівка у 1836 році поміщиком Савою Ольховським. Будучи майором у відставці, Сава Васильович отримав поселення від Катерини II.",
    ],
    "images": [
      "/img/portfolio/2010/restavratsiyastaroyi-tsehly-1.jpg",
      "/img/portfolio/2010/restavratsiyastaroyi-tsehly-2.jpg",
      "/img/portfolio/2010/restavratsiyastaroyi-tsehly-3.jpg",
      "/img/portfolio/2010/restavratsiyastaroyi-tsehly-4.jpg",
    ]
  },
  {
    "id": "restavratsiya-fasadu",
    "year": 2010,
    "title": "Реставрація фасаду",
    "image": "/img/portfolio/cards/restavratsiya-fasadu-khire-kharkiv.jpg",
    "place": "ХНУРЕ (м. Харків), Україна",
    "technologies": ["Очистка, реставрація та захист фасадів"],
    "body": "Ми пишаємося тим, що більшість фасадів на території Харківського Інституту Радіоелектроніки відреставровано за нашими технологіями.",
    "descr": [
      "На фото – реставрація одного з перших фасадів за нашою участю."
    ],
    "images": [
      "/img/portfolio/2010/restavratsiya-fasadu-1.jpg",
      "/img/portfolio/2010/restavratsiya-fasadu-2.jpg",
      "/img/portfolio/2010/restavratsiya-fasadu-3.jpg",
      "/img/portfolio/2010/restavratsiya-fasadu-4.jpg",
      "/img/portfolio/2010/restavratsiya-fasadu-5.jpg",
    ]
  },
  {
    "id": "hidroizolyatsiya-starym-dobrym-izofleksom",
    "year": 2010,
    "title": "Гідроізоляція старим-добрим Ізофлексом",
    "image": "/img/portfolio/cards/hidroizolyatsiya-starym-dobrym-izofleksom.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Очистка, реставрація та захист фасадів", "Торкетування", "Гідроізоляція"],
    "body": "Виконували гідроізоляцію 'старим - добрим' 'Ізофлекс'.",
    "descr": [
      "Багато наших Клієнтів знають і заслужено поважають цей матеріал за комбінацію простоти у нанесенні та надійності. Цей еластичний матеріал має відмінну адгезію практично до будь-яких будматеріалів (навіть до дерева). На фото видно, що матеріал довелося наносити на стяжку, яка тріснула у багатьох місцях. 'Ізофлекс' цього не боїться і з гідністю закриває всі тріщини."
    ],
    "images": [
      "/img/portfolio/2010/hidroizolyatsiya-starym-dobrym-izofleksom-1.jpg",
      "/img/portfolio/2010/hidroizolyatsiya-starym-dobrym-izofleksom-2.jpg",
      "/img/portfolio/2010/hidroizolyatsiya-starym-dobrym-izofleksom-3.jpg",
      "/img/portfolio/2010/hidroizolyatsiya-starym-dobrym-izofleksom-4.jpg",
      "/img/portfolio/2010/hidroizolyatsiya-starym-dobrym-izofleksom-5.jpg",
      "/img/portfolio/2010/hidroizolyatsiya-starym-dobrym-izofleksom-6.jpg",
    ]
  },
  {
    "id": "aeroport",
    "year": 2011,
    "title": "Аеропорт",
    "image": "/img/portfolio/cards/aeroport.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Гідроізоляція", "Ремонт бетону та залізобетону", "Утеплення та модернізація"],
    "body": "Ми брали участь у реставрації архітектурних елементів старого терміналу Харківського аеропорту",
    "descr": [
      "Пам'ятник архітектури. Аеропорт 2 класу, здатний приймати літаки Airbus A310, Airbus A-320, Boeing-737, Boeing-757, Douglas MD-80, Embraer 145, Ту-154, Іл-76, Як-42 і більш легкі, Boeing 767, Airbus A330, Ан-124 з обмеженнями, а також гелікоптери всіх типів.",
      "Плюс повне відновлення головного шпиля – посилення колон, гідроізоляція плоских частин, фінішне оздоблення.",
    ],
    "images": [
      "/img/portfolio/2011/aeroport-1.jpg",
      "/img/portfolio/2011/aeroport-2.jpg",
      "/img/portfolio/2011/aeroport-3.jpg",
      "/img/portfolio/2011/aeroport-4.jpg",
      "/img/portfolio/2011/aeroport-5.jpg",
      "/img/portfolio/2011/aeroport-6.jpg",
      "/img/portfolio/2011/aeroport-7.jpg",
      "/img/portfolio/2011/aeroport-8.jpg",
      "/img/portfolio/2011/aeroport-9.jpg",
      "/img/portfolio/2011/aeroport-10.jpg",
      "/img/portfolio/2011/aeroport-11.jpg",
      "/img/portfolio/2011/aeroport-12.jpg",
      "/img/portfolio/2011/aeroport-13.jpg",
      "/img/portfolio/2011/aeroport-14.jpg",
      "/img/portfolio/2011/aeroport-15.jpg"
    ]
  },
  {
    "id": "kharkivskyy-natsionalnyy-universytet-im-v-n-karazina",
    "year": 2012,
    "title": "Харківський національний університет ім. В. Н. Каразіна",
    "image": "/img/portfolio/cards/harkovskij-naczionalnyj-universitet-im.-v.-n.-karazina.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Очистка, реставрація та захист фасадів", "Гідроізоляція"],
    "body": "Ми брали участь у реставрації такого значного об'єкту Харкова, як Харківський Національний Університет ім. В. Н. Каразіна",
    "descr": [
      ""
    ],
    "images": [
      "/img/portfolio/2012/kharkivskyy-natsionalnyy-universytet-im-v-n-karazina-1.jpg",
      "/img/portfolio/2012/kharkivskyy-natsionalnyy-universytet-im-v-n-karazina-2.jpg",
      "/img/portfolio/2012/kharkivskyy-natsionalnyy-universytet-im-v-n-karazina-3.jpg",
      "/img/portfolio/2012/kharkivskyy-natsionalnyy-universytet-im-v-n-karazina-4.jpg",
      "/img/portfolio/2012/kharkivskyy-natsionalnyy-universytet-im-v-n-karazina-5.jpg",
      "/img/portfolio/2012/kharkivskyy-natsionalnyy-universytet-im-v-n-karazina-6.jpg",
      "/img/portfolio/2012/kharkivskyy-natsionalnyy-universytet-im-v-n-karazina-7.jpg",
      "/img/portfolio/2012/kharkivskyy-natsionalnyy-universytet-im-v-n-karazina-8.jpg"
    ]
  },
  {
    "id": "natsbank-ukrayiny",
    "year": 2013,
    "title": "Нацбанк України",
    "image": "/img/portfolio/cards/natsbank-ukrayiny.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Очистка, реставрація та захист фасадів"],
    "body": "Будівля Нацбанку України у Дніпрі – пам'ятка архітектури.",
    "descr": [
      "Наша компанія брала участь у реставрації та приведенні фасаду у той вид, яким Ви можете милуватися тепер. Плюс утеплення дворових фасадів."
    ],
    "images": [
      "/img/portfolio/2013/natsbank-ukrayiny.jpg"
    ]
  },
  {
    "id": "restavratsiya-fasadu-instytut-imunolohiyi-im-i-i-mechnykova",
    "year": 2013,
    "title": "Реставрація фасаду Інститут імунології ім. І.І. Мечникова",
    "image": "/img/portfolio/cards/restavracziya-fasada-institut-immunologii-im-mechnikova.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Очистка, реставрація та захист фасадів", "Склеювання тріщин", "Ремонт бетону та залізобетону"],
    "body": "Ми брали участь у реставрації архітектурних елементів старої будівлі.",
    "descr": [
      "Відновлювали декоративні елементи фасаду",
      "А також повне відновлення грифонів."
    ],
    "images": [
      "/img/portfolio/2013/restavratsiya-fasadu-instytut-imunolohiyi-im-i-i-Mechnykova-1.jpg",
      "/img/portfolio/2013/restavratsiya-fasadu-instytut-imunolohiyi-im-i-i-Mechnykova-2.jpg",
      "/img/portfolio/2013/restavratsiya-fasadu-instytut-imunolohiyi-im-i-i-Mechnykova-3.jpg",
      "/img/portfolio/2013/restavratsiya-fasadu-instytut-imunolohiyi-im-i-i-Mechnykova-4.jpg",
      "/img/portfolio/2013/restavratsiya-fasadu-instytut-imunolohiyi-im-i-i-Mechnykova-5.jpg",
      "/img/portfolio/2013/restavratsiya-fasadu-instytut-imunolohiyi-im-i-i-Mechnykova-6.jpg",
      "/img/portfolio/2013/restavratsiya-fasadu-instytut-imunolohiyi-im-i-i-Mechnykova-7.jpg",
      "/img/portfolio/2013/restavratsiya-fasadu-instytut-imunolohiyi-im-i-i-Mechnykova-8.jpg",
      "/img/portfolio/2013/restavratsiya-fasadu-instytut-imunolohiyi-im-i-i-Mechnykova-9.jpg",
      "/img/portfolio/2013/restavratsiya-fasadu-instytut-imunolohiyi-im-i-i-Mechnykova-10.jpg",
      "/img/portfolio/2013/restavratsiya-fasadu-instytut-imunolohiyi-im-i-i-Mechnykova-11.jpg",
      "/img/portfolio/2013/restavratsiya-fasadu-instytut-imunolohiyi-im-i-i-Mechnykova-12.jpg",
      "/img/portfolio/2013/restavratsiya-fasadu-instytut-imunolohiyi-im-i-i-Mechnykova-13.jpg"
    ]
  },
  {
    "id": "kharkivskyy-derzhavnyy-akademichnyy-teatr-lyalok-im-v-a-afanasyeva",
    "year": 2014,
    "title": "Харківський державний академічний театр ляльок ім. В. А. Афанасьєва",
    "image": "/img/portfolio/cards/gidroizolyacziya-krovli-harkovskij-gosudarstvennyj-akademicheskij-teatr-lyalok.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Ремонт бетону та залізобетону", "Гідроізоляція", "Склеювання тріщин"],
    "body": "",
    "descr": [
      ""
    ],
    "images": [
      "/img/portfolio/2014/kharkivskyy-derzhavnyy-akademichnyy-teatr-lyalok-im-v-a-afanasyeva-1.jpg",
      "/img/portfolio/2014/kharkivskyy-derzhavnyy-akademichnyy-teatr-lyalok-im-v-a-afanasyeva-2.jpg",
      "/img/portfolio/2014/kharkivskyy-derzhavnyy-akademichnyy-teatr-lyalok-im-v-a-afanasyeva-3.jpg",
      "/img/portfolio/2014/kharkivskyy-derzhavnyy-akademichnyy-teatr-lyalok-im-v-a-afanasyeva-4.jpg",
      "/img/portfolio/2014/kharkivskyy-derzhavnyy-akademichnyy-teatr-lyalok-im-v-a-afanasyeva-5.jpg",
      "/img/portfolio/2014/kharkivskyy-derzhavnyy-akademichnyy-teatr-lyalok-im-v-a-afanasyeva-6.jpg",
      "/img/portfolio/2014/kharkivskyy-derzhavnyy-akademichnyy-teatr-lyalok-im-v-a-afanasyeva-7.jpg",
      "/img/portfolio/2014/kharkivskyy-derzhavnyy-akademichnyy-teatr-lyalok-im-v-a-afanasyeva-8.jpg",
      "/img/portfolio/2014/kharkivskyy-derzhavnyy-akademichnyy-teatr-lyalok-im-v-a-afanasyeva-9.jpg",
      "/img/portfolio/2014/kharkivskyy-derzhavnyy-akademichnyy-teatr-lyalok-im-v-a-afanasyeva-10.jpg",
      "/img/portfolio/2014/kharkivskyy-derzhavnyy-akademichnyy-teatr-lyalok-im-v-a-afanasyeva-11.jpg",
      "/img/portfolio/2014/kharkivskyy-derzhavnyy-akademichnyy-teatr-lyalok-im-v-a-afanasyeva-12.jpg",
      "/img/portfolio/2014/kharkivskyy-derzhavnyy-akademichnyy-teatr-lyalok-im-v-a-afanasyeva-13.jpg",
      "/img/portfolio/2014/kharkivskyy-derzhavnyy-akademichnyy-teatr-lyalok-im-v-a-afanasyeva-14.jpg",
      "/img/portfolio/2014/kharkivskyy-derzhavnyy-akademichnyy-teatr-lyalok-im-v-a-afanasyeva-15.jpg",
      "/img/portfolio/2014/kharkivskyy-derzhavnyy-akademichnyy-teatr-lyalok-im-v-a-afanasyeva-16.jpg",
      "/img/portfolio/2014/kharkivskyy-derzhavnyy-akademichnyy-teatr-lyalok-im-v-a-afanasyeva-17.jpg",
      "/img/portfolio/2014/kharkivskyy-derzhavnyy-akademichnyy-teatr-lyalok-im-v-a-afanasyeva-18.jpg",
      "/img/portfolio/2014/kharkivskyy-derzhavnyy-akademichnyy-teatr-lyalok-im-v-a-afanasyeva-19.jpg"
    ]
  },
  {
    "id": "zavod-starplast",
    "year": 2014,
    "title": "Завод «Старпласт»",
    "image": "/img/portfolio/cards/zavod-starplast.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Утеплення та модернізація", "Ремонт бетону та залізобетону", "Гідроізоляція", "Торкетування"],
    "body": "Наші шановні Замовники – завод 'Старпласт' (Харків).",
    "descr": [
      "Верхній ряд облицювальних панелей через неправильне злив води з покрівлі виявився сильно зруйнованим.",
      "Для відновлення бетону ми вирішили застосувати технологію торкретування (нанесення на поверхню бетону під тиском). Роботи велися альпіністами на висоті зі спеціально сконструйованих колисок. Відновили захисний шар та загерметизовані.",
    ],
    "images": [
      "/img/portfolio/2014/zavod-starplast-1.jpg",
      "/img/portfolio/2014/zavod-starplast-2.jpg",
      "/img/portfolio/2014/zavod-starplast-3.jpg",
      "/img/portfolio/2014/zavod-starplast-4.jpg",
      "/img/portfolio/2014/zavod-starplast-5.jpg",
      "/img/portfolio/2014/zavod-starplast-6.jpg",
      "/img/portfolio/2014/zavod-starplast-7.jpg",
      "/img/portfolio/2014/zavod-starplast-8.jpg",
    ]
  },
  {
    "id": "khnure-2014",
    "year": 2014,
    "title": "ХНУРЕ",
    "image": "/img/portfolio/cards/khnure.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Очистка, реставрація та захист фасадів"],
    "body": "Покриття літер поліуретановою мастикою виробництва ISOMAT(Греція).",
    "descr": [
      "В даному випадку нам потрібні були такі якості матеріалу як 'стійкість до ультрафіолету та перепадів температури'."
    ],
    "images": [
      "/img/portfolio/2014/khnure-2014.jpg"
    ]
  },
  {
    "id": "remont-skhodyn-useredyni-prymishchennya-khnure",
    "year": 2015,
    "title": "Ремонт сходин усередині приміщення ХНУРЕ",
    "image": "/img/portfolio/cards/remont-lestnichnyh-marshej-vnutri-primischenya-khnure.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Очистка, реставрація та захист фасадів", "Склеювання тріщин", "Ремонт бетону та залізобетону", "Гідроізоляція"],
    "body": "",
    "descr": [
      ""
    ],
    "images": [
      "/img/portfolio/2015/remont-skhodyn-useredyni-prymishchennya-khnure-1.jpg",
      "/img/portfolio/2015/remont-skhodyn-useredyni-prymishchennya-khnure-2.jpg",
      "/img/portfolio/2015/remont-skhodyn-useredyni-prymishchennya-khnure-3.jpg",
      "/img/portfolio/2015/remont-skhodyn-useredyni-prymishchennya-khnure-4.jpg",
      "/img/portfolio/2015/remont-skhodyn-useredyni-prymishchennya-khnure-5.jpg",
      "/img/portfolio/2015/remont-skhodyn-useredyni-prymishchennya-khnure-6.jpg",
      "/img/portfolio/2015/remont-skhodyn-useredyni-prymishchennya-khnure-7.jpg",
      "/img/portfolio/2015/remont-skhodyn-useredyni-prymishchennya-khnure-8.jpg",
      "/img/portfolio/2015/remont-skhodyn-useredyni-prymishchennya-khnure-9.jpg",
      "/img/portfolio/2015/remont-skhodyn-useredyni-prymishchennya-khnure-10.jpg",
      "/img/portfolio/2015/remont-skhodyn-useredyni-prymishchennya-khnure-11.jpg",
      "/img/portfolio/2015/remont-skhodyn-useredyni-prymishchennya-khnure-12.jpg",
      "/img/portfolio/2015/remont-skhodyn-useredyni-prymishchennya-khnure-13.jpg",
      "/img/portfolio/2015/remont-skhodyn-useredyni-prymishchennya-khnure-14.jpg",
      "/img/portfolio/2015/remont-skhodyn-useredyni-prymishchennya-khnure-15.jpg",
      "/img/portfolio/2015/remont-skhodyn-useredyni-prymishchennya-khnure-16.jpg",
      "/img/portfolio/2015/remont-skhodyn-useredyni-prymishchennya-khnure-17.jpg",
    ]
  },
  {
    "id": "hidroizolyatsiya-baseynu",
    "year": 2016,
    "title": "Гідроізоляція басейну",
    "image": "/img/portfolio/cards/gidroizolyacziya-bassejna.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Гідроізоляція"],
    "body": "Восени закінчено ще один об'єкт – гідроізоляція басейну матеріалом “Епоксикоут-С”, ISOMAT (Греція).",
    "descr": [
      "Це покриття поєднує в собі кілька функцій: естетика, стійкість до ультрафіолету та морозу (як бачите, басейн просто неба)."
    ],
    "images": [
      "/img/portfolio/2016/hidroizolyatsiya-baseynu-1.jpg",
      "/img/portfolio/2016/hidroizolyatsiya-baseynu-2.jpg",
      "/img/portfolio/2016/hidroizolyatsiya-baseynu-3.jpg",
      "/img/portfolio/2016/hidroizolyatsiya-baseynu-4.jpg",
    ]
  },
  {
    "id": "hidroizolyatsiya-deformatsiynykh-shviv",
    "year": 2016,
    "title": "Гідроізоляція деформаційних швів",
    "image": "/img/portfolio/cards/gidroizolyacziya-deformaczionnyh-shviv.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Гідроізоляція"],
    "body": "З полімербітумною гідроізоляцією 'Ізофлекс ПУ- 560 ВТ' відмінно вирішується таке завдання, як гідроізоляція деформаційних швів.",
    "descr": [
      "Коефіцієнт розширення – 1500%, армований стрічкою – витримає будь-які рухи шва.",
      "2 - компонентна поліуретан - бітумна рідка мастика для гідроізоляції.",
      "Створює суцільний еластичний гідроізолюючий шар, без швів та стиків. Має відмінну адгезію до різних типів поверхні: бетон, цементна стяжка, бітумні покриття і т.д. Застосовується для гідроізоляції підземних конструкцій, зелених покрівель і т.д., а також для нанесення під плитку в кухнях, ванних кімнатах, на балконах та терасах після попереднього посипання фінішного шару мембрани кварцовим піском.",
      "ISOFLEX-PU 560 BT також застосовується як герметик, що самовирівнюється, для температурних і деформаційних швів.",
    ],
    "images": [
      "/img/portfolio/2016/hidroizolyatsiya-deformatsiynykh-shviv-1.jpg",
      "/img/portfolio/2016/hidroizolyatsiya-deformatsiynykh-shviv-2.jpg",
      "/img/portfolio/2016/hidroizolyatsiya-deformatsiynykh-shviv-3.jpg",
      "/img/portfolio/2016/hidroizolyatsiya-deformatsiynykh-shviv-4.jpg",
      "/img/portfolio/2016/hidroizolyatsiya-deformatsiynykh-shviv-5.jpg",
      "/img/portfolio/2016/hidroizolyatsiya-deformatsiynykh-shviv-6.jpg",
      "/img/portfolio/2016/hidroizolyatsiya-deformatsiynykh-shviv-7.jpg",
    ]
  },
  {
    "id": "hidroizolyatsiya-prokhidnykh-elementiv",
    "year": 2016,
    "title": "Гідроізоляція прохідних елементів",
    "image": "/img/portfolio/cards/gidroizolyacziya-prohidnyh-elementiv.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Гідроізоляція"],
    "body": "Ще один приклад із серії 'малий золотник, але якщо його не зробити правильно, потім проблем купа буде'.",
    "descr": [
      "У товщу стіни запресовується водореактивний шнур, розчин для запресування додається добавка 'Адипласт' і Фібра поліпропіленова. (Якщо не хочеться возитися, то можна взяти готовий ремонтний розчин 'Мегакрет - 40' або 'Рапікрет', що швидко схоплюється.) Викружка робиться нашим поліуретановим герметиком, а заключна гідроізоляція (чорна на знімку) - 'Ізофлекс - ПУ 560 ВТ' з коефіцієнтом подовження %!",
      "Вода тут точно не пройде!",
    ],
    "images": [
      "/img/portfolio/2016/hidroizolyatsiya-prokhidnykh-elementiv-1.jpg",
      "/img/portfolio/2016/hidroizolyatsiya-prokhidnykh-elementiv-2.jpg",
      "/img/portfolio/2016/hidroizolyatsiya-prokhidnykh-elementiv-3.jpg",
      "/img/portfolio/2016/hidroizolyatsiya-prokhidnykh-elementiv-4.jpg",
      "/img/portfolio/2016/hidroizolyatsiya-prokhidnykh-elementiv-5.jpg",
      "/img/portfolio/2016/hidroizolyatsiya-prokhidnykh-elementiv-6.jpg",
      "/img/portfolio/2016/hidroizolyatsiya-prokhidnykh-elementiv-7.jpg",
      "/img/portfolio/2016/hidroizolyatsiya-prokhidnykh-elementiv-8.jpg",
    ]
  },
  {
    "id": "hidroizolyatsiya-skhodiv",
    "year": 2018,
    "title": "Гідроізоляція сходів",
    "image": "/img/portfolio/cards/gidroizolyacziya-stupenej-vul-gvardiyciv-shiroinciv-kharkov.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Гідроізоляція", "Склеювання тріщин", "Ремонт бетону та залізобетону"],
    "body": "Гідроізоляція сходів вул. Гвардійців широнінців (м. Харків)",
    "descr": [
      ""
    ],
    "images": [
      "/img/portfolio/2018/hidroizolyatsiya-skhodiv-1.jpg",
      "/img/portfolio/2018/hidroizolyatsiya-skhodiv-2.jpg",
      "/img/portfolio/2018/hidroizolyatsiya-skhodiv-3.jpg",
      "/img/portfolio/2018/hidroizolyatsiya-skhodiv-4.jpg",
      "/img/portfolio/2018/hidroizolyatsiya-skhodiv-5.jpg",
      "/img/portfolio/2018/hidroizolyatsiya-skhodiv-6.jpg",
      "/img/portfolio/2018/hidroizolyatsiya-skhodiv-7.jpg",
      "/img/portfolio/2018/hidroizolyatsiya-skhodiv-8.jpg",
      "/img/portfolio/2018/hidroizolyatsiya-skhodiv-9.jpg",
      "/img/portfolio/2018/hidroizolyatsiya-skhodiv-10.jpg",
      "/img/portfolio/2018/hidroizolyatsiya-skhodiv-11.jpg",
      "/img/portfolio/2018/hidroizolyatsiya-skhodiv-12.jpg",
      "/img/portfolio/2018/hidroizolyatsiya-skhodiv-13.jpg",
      "/img/portfolio/2018/hidroizolyatsiya-skhodiv-14.jpg",
    ]
  },
  {
    "id": "kaskad-baseyniv-u-parku-kultury-ta-vidpochynku-im-kvitky-osnovyanenka",
    "year": 2018,
    "title": "Каскад басейнів у парку культури та відпочинку ім. Квітки-Основ'яненка",
    "image": "/img/portfolio/cards/kaskad-baseyniv-u-parku-kultury-ta-vidpochynku-im-kvitky-osnov'yanenka.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Гідроізоляція", "Склеювання тріщин", "Ремонт бетону та залізобетону"],
    "body": "У 2018 році до нас звернувся замовник із проханням допомогти відреставрувати каскад басейнів у Парку культури та відпочинку ім. Квітки-Основ'яненка.",
    "descr": [
      "Завдання не з простих, але ми з нею впоралися. Дивіться, що з цього вийшло."
    ],
    "images": [
      "/img/portfolio/2018/kaskad-baseyniv-u-parku-kultury-ta-vidpochynku-im-kvitky-osnovyanenka-1.jpg",
      "/img/portfolio/2018/kaskad-baseyniv-u-parku-kultury-ta-vidpochynku-im-kvitky-osnovyanenka-2.jpg",
    ]
  },
  {
    "id": "restavratsiya-fasadu-budivli-z-chervonoyi-tsehlyny",
    "year": 2018,
    "title": "Реставрація фасаду будівлі з червоної цеглини",
    "image": "/img/portfolio/cards/restavracziya-fasada-budivli-z-chervonoiy-cegli-vul-malinovskogo.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Гідроізоляція", "Склеювання тріщин", "Ремонт бетону та залізобетону", "Очистка, реставрація та захист фасадів"],
    "body": "Минулого року до нас звернувся замовник із проханням відреставрувати стару будівлю(таких фасадів по м.Харкові дуже багато) ",
    "descr": [
      "Маючи 20-річний досвід роботи у реставрації, ми з радістю взялися за цей об'єкт.",
      "Обстеживши будівлю виявили безліч проблем: стара цегла зруйнувалася, тріщини в самому фасаді, протікання води тощо. При реставрації цієї будівлі ми застосували більшість своїх розроблених технологій.",
      "Дивіться, що з цього вийшло…",
    ],
    "images": [
      "/img/portfolio/2018/restavratsiya-fasadu-budivli-z-chervonoyi-tsehlyny-1.jpg",
      "/img/portfolio/2018/restavratsiya-fasadu-budivli-z-chervonoyi-tsehlyny-2.jpg",
      "/img/portfolio/2018/restavratsiya-fasadu-budivli-z-chervonoyi-tsehlyny-3.jpg",
      "/img/portfolio/2018/restavratsiya-fasadu-budivli-z-chervonoyi-tsehlyny-4.jpg",
      "/img/portfolio/2018/restavratsiya-fasadu-budivli-z-chervonoyi-tsehlyny-5.jpg",
      "/img/portfolio/2018/restavratsiya-fasadu-budivli-z-chervonoyi-tsehlyny-6.jpg",
      "/img/portfolio/2018/restavratsiya-fasadu-budivli-z-chervonoyi-tsehlyny-7.jpg",
      "/img/portfolio/2018/restavratsiya-fasadu-budivli-z-chervonoyi-tsehlyny-8.jpg",
      "/img/portfolio/2018/restavratsiya-fasadu-budivli-z-chervonoyi-tsehlyny-9.jpg",
      "/img/portfolio/2018/restavratsiya-fasadu-budivli-z-chervonoyi-tsehlyny-10.jpg",
      "/img/portfolio/2018/restavratsiya-fasadu-budivli-z-chervonoyi-tsehlyny-11.jpg",
      "/img/portfolio/2018/restavratsiya-fasadu-budivli-z-chervonoyi-tsehlyny-12.jpg",
      "/img/portfolio/2018/restavratsiya-fasadu-budivli-z-chervonoyi-tsehlyny-13.jpg",
      "/img/portfolio/2018/restavratsiya-fasadu-budivli-z-chervonoyi-tsehlyny-14.jpg",
      "/img/portfolio/2018/restavratsiya-fasadu-budivli-z-chervonoyi-tsehlyny-15.jpg",
    ]
  },
  {
    "id": "prystriy-hidroizolyatsiyi-vymoshchennya",
    "year": 2018,
    "title": "Пристрій гідроізоляції вимощення",
    "image": "/img/portfolio/cards/prystriy-hidroizolyatsiyi-vymoshchennya-po-vul-chernyshevskoho.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Гідроізоляція"],
    "body": "У 2020 році до нас звернувся із проханням замовник допомогти вирішити проблему із затіканням води.",
    "descr": [
      "Що з цього вдалося Ви можете побачити на цій сторінці."
    ],
    "images": [
      "/img/portfolio/2018/prystriy-hidroizolyatsiyi-vymoshchennya-1.jpg",
      "/img/portfolio/2018/prystriy-hidroizolyatsiyi-vymoshchennya-2.jpg",
      "/img/portfolio/2018/prystriy-hidroizolyatsiyi-vymoshchennya-3.jpg",
      "/img/portfolio/2018/prystriy-hidroizolyatsiyi-vymoshchennya-4.jpg",
      "/img/portfolio/2018/prystriy-hidroizolyatsiyi-vymoshchennya-5.jpg",
      "/img/portfolio/2018/prystriy-hidroizolyatsiyi-vymoshchennya-6.jpg",
      "/img/portfolio/2018/prystriy-hidroizolyatsiyi-vymoshchennya-7.jpg",
      "/img/portfolio/2018/prystriy-hidroizolyatsiyi-vymoshchennya-8.jpg",
      "/img/portfolio/2018/prystriy-hidroizolyatsiyi-vymoshchennya-9.jpg",
      "/img/portfolio/2018/prystriy-hidroizolyatsiyi-vymoshchennya-10.jpg",
      "/img/portfolio/2018/prystriy-hidroizolyatsiyi-vymoshchennya-11.jpg",
      "/img/portfolio/2018/prystriy-hidroizolyatsiyi-vymoshchennya-12.jpg",
      "/img/portfolio/2018/prystriy-hidroizolyatsiyi-vymoshchennya-13.jpg",
      "/img/portfolio/2018/prystriy-hidroizolyatsiyi-vymoshchennya-14.jpg",
      "/img/portfolio/2018/prystriy-hidroizolyatsiyi-vymoshchennya-15.jpg",
      "/img/portfolio/2018/prystriy-hidroizolyatsiyi-vymoshchennya-16.jpg",
      "/img/portfolio/2018/prystriy-hidroizolyatsiyi-vymoshchennya-17.jpg",
      "/img/portfolio/2018/prystriy-hidroizolyatsiyi-vymoshchennya-18.jpg",
      "/img/portfolio/2018/prystriy-hidroizolyatsiyi-vymoshchennya-19.jpg",
      "/img/portfolio/2018/prystriy-hidroizolyatsiyi-vymoshchennya-20.jpg",
      "/img/portfolio/2018/prystriy-hidroizolyatsiyi-vymoshchennya-21.jpg",
      "/img/portfolio/2018/prystriy-hidroizolyatsiyi-vymoshchennya-22.jpg",
      "/img/portfolio/2018/prystriy-hidroizolyatsiyi-vymoshchennya-23.jpg",
      "/img/portfolio/2018/prystriy-hidroizolyatsiyi-vymoshchennya-24.jpg",
    ]
  },
  {
    "id": "sharivskyy-zamok",
    "year": 2018,
    "title": "Шарівський замок (садиба)",
    "image": "/img/portfolio/cards/sharivskyy-zamok.jpg",
    "place": "СМТ Шарівка, Україна",
    "technologies": ["Гідроізоляція", "Очистка, реставрація та захист фасадів", "Торкетування"],
    "body": "Шарівка - білокам'яна споруда кінця XIX століття неоготичного стилю, колишня поміщицька садиба.",
    "descr": [
      "Розташована у смт Шарівка Богодухівського району Харківської області на березі річки Мерчик.",
      "Садиба заснована у селі Шарівка 1836 року поміщиком Савою Ольховським. Будучи майором у відставці, Сава Васильович отримав поселення від Катерини II.",
    ],
    "images": [
      "/img/portfolio/2018/sharivskyy-zamok-1.jpg",
      "/img/portfolio/2018/sharivskyy-zamok-2.jpg",
      "/img/portfolio/2018/sharivskyy-zamok-3.jpg",
      "/img/portfolio/2018/sharivskyy-zamok-4.jpg",
    ]
  },
  {
    "id": "armuvannya-ta-inyektuvannya-stin",
    "year": 2019,
    "title": "Армування та ін'єктування стін",
    "image": "/img/portfolio/cards/armuvannya-ta-inyektuvannya-stin-na-vul-alchevskykh.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Гідроізоляція", "Склеювання тріщин", "Посилення вуглецевими полотнами", "Ремонт бетону та залізобетону"],
    "body": "",
    "descr": [
      ""
    ],
    "images": [
      "/img/portfolio/2019/armuvannya-ta-inyektuvannya-stin-1.jpg",
      "/img/portfolio/2019/armuvannya-ta-inyektuvannya-stin-2.jpg",
      "/img/portfolio/2019/armuvannya-ta-inyektuvannya-stin-3.jpg",
      "/img/portfolio/2019/armuvannya-ta-inyektuvannya-stin-4.jpg",
      "/img/portfolio/2019/armuvannya-ta-inyektuvannya-stin-5.jpg",
      "/img/portfolio/2019/armuvannya-ta-inyektuvannya-stin-6.jpg",
      "/img/portfolio/2019/armuvannya-ta-inyektuvannya-stin-7.jpg",
      "/img/portfolio/2019/armuvannya-ta-inyektuvannya-stin-8.jpg",
      "/img/portfolio/2019/armuvannya-ta-inyektuvannya-stin-9.jpg",
      "/img/portfolio/2019/armuvannya-ta-inyektuvannya-stin-10.jpg",
      "/img/portfolio/2019/armuvannya-ta-inyektuvannya-stin-11.jpg",
      "/img/portfolio/2019/armuvannya-ta-inyektuvannya-stin-12.jpg",
      "/img/portfolio/2019/armuvannya-ta-inyektuvannya-stin-13.jpg",
      "/img/portfolio/2019/armuvannya-ta-inyektuvannya-stin-14.jpg",
      "/img/portfolio/2019/armuvannya-ta-inyektuvannya-stin-15.jpg",
      "/img/portfolio/2019/armuvannya-ta-inyektuvannya-stin-16.jpg",
      "/img/portfolio/2019/armuvannya-ta-inyektuvannya-stin-17.jpg",
      "/img/portfolio/2019/armuvannya-ta-inyektuvannya-stin-18.jpg",
      "/img/portfolio/2019/armuvannya-ta-inyektuvannya-stin-19.jpg",
      "/img/portfolio/2019/armuvannya-ta-inyektuvannya-stin-20.jpg",
      "/img/portfolio/2019/armuvannya-ta-inyektuvannya-stin-21.jpg",
    ]
  },
  {
    "id": "ochyshchennya-kolon-z-tsehly",
    "year": 2019,
    "title": "Очищення колон з цегли",
    "image": "/img/portfolio/cards/ochischennya-stin-z-cegli-po-vul-kaczarskaya.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Ремонт бетону та залізобетону", "Склеювання тріщин", "Очистка, реставрація та захист фасадів"],
    "body": "Минулого року до нас звернувся із проханням замовник допомогти очистити фасад будівлі з білої цегли.",
    "descr": [
      "Протягом багатьох років фасад не мав ніякого догляду, і на ньому зібралася велика кількість пилу, вихлопних газів, кіптяви, бруду та інших речовин.",
      "І фасад втратив свою привабливість.",
      "Ми вирішили допомогти. Розробили ТЕХНОЛОГІЮ ДЛЯ ОЧИЩЕННЯ ФАСАДУ БУДИНКУ.",
      "Що з цього вдалося Ви можете побачити на цій сторінці."
    ],
    "images": [
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-1.jpg",
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-2.jpg",
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-3.jpg",
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-4.jpg",
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-5.jpg",
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-6.jpg",
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-7.jpg",
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-8.jpg",
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-9.jpg",
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-10.jpg",
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-11.jpg",
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-12.jpg",
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-13.jpg",
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-14.jpg",
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-15.jpg",
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-16.jpg",
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-17.jpg",
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-18.jpg",
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-19.jpg",
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-20.jpg",
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-21.jpg",
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-22.jpg",
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-23.jpg",
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-24.jpg",
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-25.jpg",
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-26.jpg",
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-27.jpg",
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-28.jpg",
      "/img/portfolio/2019/ochyshchennya-kolon-z-tsehly-29.jpg",
    ]
  },
  {
    "id": "piskostruyne-ochyshchennya-stin-z-chervonoyi-tsehly",
    "year": 2019,
    "title": "Піскоструйне очищення стін з червоної цегли",
    "image": "/img/portfolio/cards/piskostruyne-ochischennya-stin-z-chervonoy-cegli.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Очистка, реставрація та захист фасадів"],
    "body": "Є звичайні піскоструминні установки, в яких пісок вилітає «в лоб» і вигризає в цеглині ​​вибоїни.",
    "descr": [
      "А ми застосовуємо піскоструминну установку фірми «ROTEK» (Німеччина), в якій пісок закручується по спіралі і підлітає до поверхні «дотичної».",
      "Цим забезпечується щадне очищення поверхні. Ми можемо з газети зняти літери, не пошкодивши папір!",
    ],
    "images": [
      "/img/portfolio/2019/piskostruyne-ochyshchennya-stin-z-chervonoyi-tsehly-1.jpg",
      "/img/portfolio/2019/piskostruyne-ochyshchennya-stin-z-chervonoyi-tsehly-2.jpg",
      "/img/portfolio/2019/piskostruyne-ochyshchennya-stin-z-chervonoyi-tsehly-3.jpg",
      "/img/portfolio/2019/piskostruyne-ochyshchennya-stin-z-chervonoyi-tsehly-4.jpg",
      "/img/portfolio/2019/piskostruyne-ochyshchennya-stin-z-chervonoyi-tsehly-5.jpg",
      "/img/portfolio/2019/piskostruyne-ochyshchennya-stin-z-chervonoyi-tsehly-6.jpg",
      "/img/portfolio/2019/piskostruyne-ochyshchennya-stin-z-chervonoyi-tsehly-7.jpg",
      "/img/portfolio/2019/piskostruyne-ochyshchennya-stin-z-chervonoyi-tsehly-8.jpg",
      "/img/portfolio/2019/piskostruyne-ochyshchennya-stin-z-chervonoyi-tsehly-9.jpg",
      "/img/portfolio/2019/piskostruyne-ochyshchennya-stin-z-chervonoyi-tsehly-10.jpg",
      "/img/portfolio/2019/piskostruyne-ochyshchennya-stin-z-chervonoyi-tsehly-11.jpg",
      "/img/portfolio/2019/piskostruyne-ochyshchennya-stin-z-chervonoyi-tsehly-12.jpg",
    ]
  },
  {
    "id": "remont-ploskoyi-pokrivli",
    "year": 2019,
    "title": "Ремонт плоскої покрівлі",
    "image": "/img/portfolio/cards/remont-ploskoj-pokrivli-po-vul-gv-shironinczev-45.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Очистка, реставрація та захист фасадів", "Гідроізоляція"],
    "body": "Ремонт плоскої, експлуатованої покрівлі з подальшим покриттям мембраною та засипкою щебенем",
    "descr": [
      ""
    ],
    "images": [
      "/img/portfolio/2019/remont-ploskoyi-pokrivli-1.jpg",
      "/img/portfolio/2019/remont-ploskoyi-pokrivli-2.jpg",
      "/img/portfolio/2019/remont-ploskoyi-pokrivli-3.jpg",
      "/img/portfolio/2019/remont-ploskoyi-pokrivli-4.jpg",
      "/img/portfolio/2019/remont-ploskoyi-pokrivli-5.jpg",
      "/img/portfolio/2019/remont-ploskoyi-pokrivli-6.jpg",
      "/img/portfolio/2019/remont-ploskoyi-pokrivli-7.jpg",
      "/img/portfolio/2019/remont-ploskoyi-pokrivli-8.jpg",
      "/img/portfolio/2019/remont-ploskoyi-pokrivli-9.jpg",
      "/img/portfolio/2019/remont-ploskoyi-pokrivli-10.jpg",
      "/img/portfolio/2019/remont-ploskoyi-pokrivli-11.jpg",
      "/img/portfolio/2019/remont-ploskoyi-pokrivli-12.jpg",
      "/img/portfolio/2019/remont-ploskoyi-pokrivli-13.jpg",
      "/img/portfolio/2019/remont-ploskoyi-pokrivli-14.jpg",
      "/img/portfolio/2019/remont-ploskoyi-pokrivli-15.jpg",
    ]
  },
  {
    "id": "kharkivska-khoralna-synahoha-2019",
    "year": 2019,
    "title": "Харківська Хоральна синагога",
    "image": "/img/portfolio/cards/kharkivska-horalna-sinagoga-2019.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Гідроізоляція"],
    "body": "Зараз багато будинків будуються з плоским дахом, що дає можливість її подальшої експлуатації.",
    "descr": [
      "Тим самим ми розуміємо, що створюється свого роду басейн, який може накопичувати воду під час атмосферних опадів. І якщо припустимося помилки хоча б на 1%, то це спричинить безліч проблем надалі.",
      "Щоб запобігти такій проблемі покрівлю можна покрити ПВХ-мембраною. Це рулонний матеріал із високою паропроникністю.Він призначений для захисту утеплювача від вологи, що потрапляє зовні будинку, пропускають пару із самого утеплювача та захищають утеплювач від продування вітром.",
      "Як це виглядає у процесі, ми Вам і покажемо…",
    ],
    "images": [
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-1.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-2.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-3.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-4.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-5.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-6.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-7.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-8.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-9.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-10.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-11.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-12.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-13.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-14.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-15.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-16.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-17.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-18.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-19.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-20.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-21.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-22.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-23.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-24.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-25.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-26.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-27.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-28.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-29.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-30.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-31.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-32.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-33.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-34.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-35.jpg",
      "/img/portfolio/2019/kharkivska-khoralna-synahoha-2019-36.jpg",
    ]
  },
  {
    "id": "membranna-pokrivlya",
    "year": 2020,
    "title": "Мембранна покрівля",
    "image": "/img/portfolio/cards/membranna-pokrivlya-vul-danylevskoho-42.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Гідроізоляція"],
    "body": "У 2020 році до нас звернувся із проханням замовник допомогти вирішити проблему із затіканням води.",
    "descr": [
      "Що з цього вдалося Ви можете побачити на цій сторінці."
    ],
    "images": [
      "/img/portfolio/2020/membranna-pokrivlya-1.jpg",
      "/img/portfolio/2020/membranna-pokrivlya-2.jpg",
      "/img/portfolio/2020/membranna-pokrivlya-3.jpg",
      "/img/portfolio/2020/membranna-pokrivlya-4.jpg",
      "/img/portfolio/2020/membranna-pokrivlya-5.jpg",
      "/img/portfolio/2020/membranna-pokrivlya-6.jpg",
      "/img/portfolio/2020/membranna-pokrivlya-7.jpg",
      "/img/portfolio/2020/membranna-pokrivlya-8.jpg",
      "/img/portfolio/2020/membranna-pokrivlya-9.jpg",
      "/img/portfolio/2020/membranna-pokrivlya-10.jpg",
      "/img/portfolio/2020/membranna-pokrivlya-11.jpg",
      "/img/portfolio/2020/membranna-pokrivlya-12.jpg",
      "/img/portfolio/2020/membranna-pokrivlya-13.jpg",
      "/img/portfolio/2020/membranna-pokrivlya-14.jpg",
      "/img/portfolio/2020/membranna-pokrivlya-15.jpg",
      "/img/portfolio/2020/membranna-pokrivlya-16.jpg",
      "/img/portfolio/2020/membranna-pokrivlya-17.jpg",
    ]
  },
  {
    "id": "khnure-2020",
    "year": 2020,
    "title": "ХНУРЕ",
    "image": "/img/portfolio/cards/natsionalnyy-universytet-radioelektroniky.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Очистка, реставрація та захист фасадів", "Ремонт бетону та залізобетону", "Склеювання тріщин"],
    "body": "У 2020 році ми вперше використовували термопанелі для утеплення фасаду будівлі.",
    "descr": [
      "Як це виглядає Ви можете подивитись самі."
    ],
    "images": [
      "/img/portfolio/2020/khnure-2020-1.jpg",
      "/img/portfolio/2020/khnure-2020-2.jpg",
      "/img/portfolio/2020/khnure-2020-3.jpg",
      "/img/portfolio/2020/khnure-2020-4.jpg",
      "/img/portfolio/2020/khnure-2020-5.jpg",
      "/img/portfolio/2020/khnure-2020-6.jpg",
      "/img/portfolio/2020/khnure-2020-7.jpg",
      "/img/portfolio/2020/khnure-2020-8.jpg",
      "/img/portfolio/2020/khnure-2020-9.jpg",
      "/img/portfolio/2020/khnure-2020-10.jpg",
      "/img/portfolio/2020/khnure-2020-11.jpg",
      "/img/portfolio/2020/khnure-2020-12.jpg",
      "/img/portfolio/2020/khnure-2020-13.jpg",
      "/img/portfolio/2020/khnure-2020-14.jpg",
      "/img/portfolio/2020/khnure-2020-15.jpg",
      "/img/portfolio/2020/khnure-2020-16.jpg",
      "/img/portfolio/2020/khnure-2020-17.jpg",
      "/img/portfolio/2020/khnure-2020-18.jpg",
      "/img/portfolio/2020/khnure-2020-19.jpg",
      "/img/portfolio/2020/khnure-2020-20.jpg",
      "/img/portfolio/2020/khnure-2020-21.jpg",
      "/img/portfolio/2020/khnure-2020-22.jpg",
      "/img/portfolio/2020/khnure-2020-23.jpg",
      "/img/portfolio/2020/khnure-2020-24.jpg",
      "/img/portfolio/2020/khnure-2020-25.jpg",
      "/img/portfolio/2020/khnure-2020-26.jpg",
      "/img/portfolio/2020/khnure-2020-27.jpg",
    ]
  },
  {
    "id": "torkretuvannya-pidvalnoho-prymishchennya",
    "year": 2020,
    "title": "Торкретування підвального приміщення",
    "image": "/img/portfolio/cards/torkretuvannya-pidvalnoho-prymishchennya.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Гідроізоляція", "Посилення вуглецевими полотнами", "Торкетування"],
    "body": "",
    "descr": [
      ""
    ],
    "images": [
      "/img/portfolio/2020/torkretuvannya-pidvalnoho-prymishchennya-1.jpg",
      "/img/portfolio/2020/torkretuvannya-pidvalnoho-prymishchennya-2.jpg",
      "/img/portfolio/2020/torkretuvannya-pidvalnoho-prymishchennya-3.jpg",
      "/img/portfolio/2020/torkretuvannya-pidvalnoho-prymishchennya-4.jpg",
      "/img/portfolio/2020/torkretuvannya-pidvalnoho-prymishchennya-5.jpg",
      "/img/portfolio/2020/torkretuvannya-pidvalnoho-prymishchennya-6.jpg",
      "/img/portfolio/2020/torkretuvannya-pidvalnoho-prymishchennya-7.jpg",
      "/img/portfolio/2020/torkretuvannya-pidvalnoho-prymishchennya-8.jpg",
      "/img/portfolio/2020/torkretuvannya-pidvalnoho-prymishchennya-9.jpg",
      "/img/portfolio/2020/torkretuvannya-pidvalnoho-prymishchennya-10.jpg",
      "/img/portfolio/2020/torkretuvannya-pidvalnoho-prymishchennya-11.jpg",
      "/img/portfolio/2020/torkretuvannya-pidvalnoho-prymishchennya-12.jpg",
      "/img/portfolio/2020/torkretuvannya-pidvalnoho-prymishchennya-13.jpg",
      "/img/portfolio/2020/torkretuvannya-pidvalnoho-prymishchennya-14.jpg",
      "/img/portfolio/2020/torkretuvannya-pidvalnoho-prymishchennya-15.jpg",
      "/img/portfolio/2020/torkretuvannya-pidvalnoho-prymishchennya-16.jpg",
      "/img/portfolio/2020/torkretuvannya-pidvalnoho-prymishchennya-17.jpg",
      "/img/portfolio/2020/torkretuvannya-pidvalnoho-prymishchennya-18.jpg",
      "/img/portfolio/2020/torkretuvannya-pidvalnoho-prymishchennya-19.jpg",
      "/img/portfolio/2020/torkretuvannya-pidvalnoho-prymishchennya-20.jpg",
      "/img/portfolio/2020/torkretuvannya-pidvalnoho-prymishchennya-21.jpg",
      "/img/portfolio/2020/torkretuvannya-pidvalnoho-prymishchennya-22.jpg",
      "/img/portfolio/2020/torkretuvannya-pidvalnoho-prymishchennya-23.jpg",
      "/img/portfolio/2020/torkretuvannya-pidvalnoho-prymishchennya-24.jpg",
      "/img/portfolio/2020/torkretuvannya-pidvalnoho-prymishchennya-25.jpg",
      "/img/portfolio/2020/torkretuvannya-pidvalnoho-prymishchennya-26.jpg",
    ]
  },
  {
    "id": "balashivskyy-mist",
    "year": 2020,
    "title": "Балашівський міст",
    "image": "/img/portfolio/cards/balashivskyy-mist.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Торкетування", "Гідроізоляція", "Піскоструминне очищення"],
    "body": "У 2020 році гідроізоляція 'Балашівського мосту' м. Харків",
    "descr": [
      "У цьому проекті були застосовані ТЕХНОЛОГІЇ ТОРКРЕТУВАННЯ, ТЕХНОЛОГІЯ ПІСКОБУДОВНОГО ОЧИЩЕННЯ, ТЕХНОЛОГІЯ ГІДРОІЗОЛЯЦІЇ.",
      "Що з цього вдалося Ви можете побачити на цій сторінці.",
    ],
    "images": [
      "/img/portfolio/2020/balashivskyy-mist-1.jpg",
      "/img/portfolio/2020/balashivskyy-mist-2.jpg",
      "/img/portfolio/2020/balashivskyy-mist-3.jpg",
      "/img/portfolio/2020/balashivskyy-mist-4.jpg",
      "/img/portfolio/2020/balashivskyy-mist-5.jpg",
      "/img/portfolio/2020/balashivskyy-mist-6.jpg",
      "/img/portfolio/2020/balashivskyy-mist-7.jpg",
      "/img/portfolio/2020/balashivskyy-mist-8.jpg",
      "/img/portfolio/2020/balashivskyy-mist-9.jpg",
      "/img/portfolio/2020/balashivskyy-mist-10.jpg",
      "/img/portfolio/2020/balashivskyy-mist-11.jpg",
      "/img/portfolio/2020/balashivskyy-mist-12.jpg",
      "/img/portfolio/2020/balashivskyy-mist-13.jpg",
      "/img/portfolio/2020/balashivskyy-mist-14.jpg",
      "/img/portfolio/2020/balashivskyy-mist-15.jpg",
      "/img/portfolio/2020/balashivskyy-mist-16.jpg",
      "/img/portfolio/2020/balashivskyy-mist-17.jpg",
      "/img/portfolio/2020/balashivskyy-mist-18.jpg",
      "/img/portfolio/2020/balashivskyy-mist-19.jpg",
      "/img/portfolio/2020/balashivskyy-mist-20.jpg",
      "/img/portfolio/2020/balashivskyy-mist-21.jpg",
      "/img/portfolio/2020/balashivskyy-mist-22.jpg",
      "/img/portfolio/2020/balashivskyy-mist-23.jpg",
      "/img/portfolio/2020/balashivskyy-mist-24.jpg",
      "/img/portfolio/2020/balashivskyy-mist-25.jpg",
      "/img/portfolio/2020/balashivskyy-mist-26.jpg",
      "/img/portfolio/2020/balashivskyy-mist-27.jpg",
      "/img/portfolio/2020/balashivskyy-mist-28.jpg",
      "/img/portfolio/2020/balashivskyy-mist-29.jpg",
      "/img/portfolio/2020/balashivskyy-mist-30.jpg",
      "/img/portfolio/2020/balashivskyy-mist-31.jpg",
      "/img/portfolio/2020/balashivskyy-mist-32.jpg",
      "/img/portfolio/2020/balashivskyy-mist-33.jpg",
      "/img/portfolio/2020/balashivskyy-mist-34.jpg",
      "/img/portfolio/2020/balashivskyy-mist-35.jpg",
      "/img/portfolio/2020/balashivskyy-mist-36.jpg",
    ]
  },
  {
    "id": "hidroizolyatsiya-avtomyyky",
    "year": 2021,
    "title": "Гідроізоляція автомийки",
    "image": "/img/portfolio/cards/hidroizolyatsiya-avtomyyky.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Гідроізоляція"],
    "body": "",
    "descr": [
      ""
    ],
    "images": [
      "/img/portfolio/2021/hidroizolyatsiya-avtomyyky-1.jpg",
      "/img/portfolio/2021/hidroizolyatsiya-avtomyyky-2.jpg",
      "/img/portfolio/2021/hidroizolyatsiya-avtomyyky-3.jpg",
      "/img/portfolio/2021/hidroizolyatsiya-avtomyyky-4.jpg",
      "/img/portfolio/2021/hidroizolyatsiya-avtomyyky-5.jpg",
      "/img/portfolio/2021/hidroizolyatsiya-avtomyyky-6.jpg",
      "/img/portfolio/2021/hidroizolyatsiya-avtomyyky-7.jpg",
      "/img/portfolio/2021/hidroizolyatsiya-avtomyyky-8.jpg",
      "/img/portfolio/2021/hidroizolyatsiya-avtomyyky-9.jpg",
      "/img/portfolio/2021/hidroizolyatsiya-avtomyyky-10.jpg",
      "/img/portfolio/2021/hidroizolyatsiya-avtomyyky-11.jpg",
      "/img/portfolio/2021/hidroizolyatsiya-avtomyyky-12.jpg",
      "/img/portfolio/2021/hidroizolyatsiya-avtomyyky-13.jpg",
      "/img/portfolio/2021/hidroizolyatsiya-avtomyyky-14.jpg",
    ]
  },
  {
    "id": "rekonstruktsiya-ta-uteplennya-fasadu-khnure-2021",
    "year": 2021,
    "title": "Реконструкція та утеплення фасаду",
    "image": "/img/portfolio/cards/rekonstruktsiya-ta-uteplennya-fasadu-a-takozh-vlashtuvannya-membrannoyi-pokrivli-kharkivskoho-natsionalnoho-universytetu-radioelektroniky.jpg",
    "place": "ХНУРЕ (м.Харків), Україна",
    "technologies": ["Гідроізоляція", "Очистка, реставрація та захист фасадів", "Ремонт бетону та залізобетону", "Склеювання тріщин"],
    "body": "Реконструкція та утеплення фасаду, а також влаштування мембранної покрівлі Харківського національного університету радіоелектроніки",
    "descr": [
      ""
    ],
    "images": [
      "/img/portfolio/2021/rekonstruktsiya-ta-uteplennya-fasadu-khnure-2021-1.jpg",
      "/img/portfolio/2021/rekonstruktsiya-ta-uteplennya-fasadu-khnure-2021-2.jpg",
      "/img/portfolio/2021/rekonstruktsiya-ta-uteplennya-fasadu-khnure-2021-3.jpg",
      "/img/portfolio/2021/rekonstruktsiya-ta-uteplennya-fasadu-khnure-2021-4.jpg",
      "/img/portfolio/2021/rekonstruktsiya-ta-uteplennya-fasadu-khnure-2021-5.jpg",
      "/img/portfolio/2021/rekonstruktsiya-ta-uteplennya-fasadu-khnure-2021-6.jpg",
      "/img/portfolio/2021/rekonstruktsiya-ta-uteplennya-fasadu-khnure-2021-7.jpg",
      "/img/portfolio/2021/rekonstruktsiya-ta-uteplennya-fasadu-khnure-2021-8.jpg",
      "/img/portfolio/2021/rekonstruktsiya-ta-uteplennya-fasadu-khnure-2021-9.jpg",
      "/img/portfolio/2021/rekonstruktsiya-ta-uteplennya-fasadu-khnure-2021-10.jpg",
      "/img/portfolio/2021/rekonstruktsiya-ta-uteplennya-fasadu-khnure-2021-11.jpg",
      "/img/portfolio/2021/rekonstruktsiya-ta-uteplennya-fasadu-khnure-2021-12.jpg",
      "/img/portfolio/2021/rekonstruktsiya-ta-uteplennya-fasadu-khnure-2021-13.jpg",
      "/img/portfolio/2021/rekonstruktsiya-ta-uteplennya-fasadu-khnure-2021-14.jpg",
      "/img/portfolio/2021/rekonstruktsiya-ta-uteplennya-fasadu-khnure-2021-15.jpg",
      "/img/portfolio/2021/rekonstruktsiya-ta-uteplennya-fasadu-khnure-2021-16.jpg",
      "/img/portfolio/2021/rekonstruktsiya-ta-uteplennya-fasadu-khnure-2021-17.jpg",
      "/img/portfolio/2021/rekonstruktsiya-ta-uteplennya-fasadu-khnure-2021-18.jpg",
      "/img/portfolio/2021/rekonstruktsiya-ta-uteplennya-fasadu-khnure-2021-19.jpg",
      "/img/portfolio/2021/rekonstruktsiya-ta-uteplennya-fasadu-khnure-2021-20.jpg",
      "/img/portfolio/2021/rekonstruktsiya-ta-uteplennya-fasadu-khnure-2021-21.jpg",
      "/img/portfolio/2021/rekonstruktsiya-ta-uteplennya-fasadu-khnure-2021-22.jpg",
      "/img/portfolio/2021/rekonstruktsiya-ta-uteplennya-fasadu-khnure-2021-23.jpg",
      "/img/portfolio/2021/rekonstruktsiya-ta-uteplennya-fasadu-khnure-2021-24.jpg",
    ]
  },
  {
    "id": "remont-skhodyn-do-prymishchen-uipa",
    "year": 2021,
    "title": "Ремонт сходин до приміщень УІПА",
    "image": "/img/portfolio/cards/remont-shchabliv-do-prymishchen-ukrayinskoyi-inzhenerno-pedahohichnoyi-akademiyi.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Ремонт бетону та залізобетону"],
    "body": "Ремонт щаблів до приміщень Української інженерно-педагогічної академії (м. Харків)",
    "descr": [
      ""
    ],
    "images": [
      "/img/portfolio/2021/remont-skhodyn-do-prymishchen-uipa-1.png",
      "/img/portfolio/2021/remont-skhodyn-do-prymishchen-uipa-2.jpg",
      "/img/portfolio/2021/remont-skhodyn-do-prymishchen-uipa-3.jpg",
      "/img/portfolio/2021/remont-skhodyn-do-prymishchen-uipa-4.jpg",
      "/img/portfolio/2021/remont-skhodyn-do-prymishchen-uipa-5.jpg",
      "/img/portfolio/2021/remont-skhodyn-do-prymishchen-uipa-6.jpg",
      "/img/portfolio/2021/remont-skhodyn-do-prymishchen-uipa-7.jpg",
      "/img/portfolio/2021/remont-skhodyn-do-prymishchen-uipa-8.jpg",
      "/img/portfolio/2021/remont-skhodyn-do-prymishchen-uipa-9.jpg",
      "/img/portfolio/2021/remont-skhodyn-do-prymishchen-uipa-10.jpg",
      "/img/portfolio/2021/remont-skhodyn-do-prymishchen-uipa-11.jpg",
      "/img/portfolio/2021/remont-skhodyn-do-prymishchen-uipa-12.jpg",
      "/img/portfolio/2021/remont-skhodyn-do-prymishchen-uipa-13.jpg",
      "/img/portfolio/2021/remont-skhodyn-do-prymishchen-uipa-14.jpg",
      "/img/portfolio/2021/remont-skhodyn-do-prymishchen-uipa-15.jpg",
      "/img/portfolio/2021/remont-skhodyn-do-prymishchen-uipa-16.jpg",
      "/img/portfolio/2021/remont-skhodyn-do-prymishchen-uipa-17.jpg",
      "/img/portfolio/2021/remont-skhodyn-do-prymishchen-uipa-18.jpg",
      "/img/portfolio/2021/remont-skhodyn-do-prymishchen-uipa-19.jpg",
      "/img/portfolio/2021/remont-skhodyn-do-prymishchen-uipa-20.jpg",
      "/img/portfolio/2021/remont-skhodyn-do-prymishchen-uipa-21.jpg",
      "/img/portfolio/2021/remont-skhodyn-do-prymishchen-uipa-22.jpg",
      "/img/portfolio/2021/remont-skhodyn-do-prymishchen-uipa-23.jpg",
    ]
  },
  {
    "id": "skleyuvannya-trishchyn-tsehlyanykh-stin",
    "year": 2021,
    "title": "Склеювання тріщин цегляних стін",
    "image": "/img/portfolio/cards/skleyuvannya-trishchyn-tsehlyanykh-stin–pr-t-heroyiv-kharkova-275.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Гідроізоляція", "Ремонт бетону та залізобетону", "Склеювання тріщин"],
    "body": "У лютому 2021 року ми провели ремонт старої будівлі методом ін'єкції.",
    "descr": [
      "Склеювали цегляні стіни на 1-му та 2-му поверхах нежитлової будівлі."
    ],
    "images": [
      "/img/portfolio/2021/skleyuvannya-trishchyn-tsehlyanykh-stin-1.jpg",
      "/img/portfolio/2021/skleyuvannya-trishchyn-tsehlyanykh-stin-2.jpg",
      "/img/portfolio/2021/skleyuvannya-trishchyn-tsehlyanykh-stin-3.jpg",
      "/img/portfolio/2021/skleyuvannya-trishchyn-tsehlyanykh-stin-4.jpg",
      "/img/portfolio/2021/skleyuvannya-trishchyn-tsehlyanykh-stin-5.jpg",
      "/img/portfolio/2021/skleyuvannya-trishchyn-tsehlyanykh-stin-6.jpg",
      "/img/portfolio/2021/skleyuvannya-trishchyn-tsehlyanykh-stin-7.jpg",
      "/img/portfolio/2021/skleyuvannya-trishchyn-tsehlyanykh-stin-8.jpg",
      "/img/portfolio/2021/skleyuvannya-trishchyn-tsehlyanykh-stin-9.jpg",
      "/img/portfolio/2021/skleyuvannya-trishchyn-tsehlyanykh-stin-10.jpg",
      "/img/portfolio/2021/skleyuvannya-trishchyn-tsehlyanykh-stin-11.jpg",
      "/img/portfolio/2021/skleyuvannya-trishchyn-tsehlyanykh-stin-12.jpg",
      "/img/portfolio/2021/skleyuvannya-trishchyn-tsehlyanykh-stin-13.jpg",
      "/img/portfolio/2021/skleyuvannya-trishchyn-tsehlyanykh-stin-14.jpg",
      "/img/portfolio/2021/skleyuvannya-trishchyn-tsehlyanykh-stin-15.jpg",
      "/img/portfolio/2021/skleyuvannya-trishchyn-tsehlyanykh-stin-16.jpg",
      "/img/portfolio/2021/skleyuvannya-trishchyn-tsehlyanykh-stin-17.jpg",
      "/img/portfolio/2021/skleyuvannya-trishchyn-tsehlyanykh-stin-18.jpg",
      "/img/portfolio/2021/skleyuvannya-trishchyn-tsehlyanykh-stin-19.jpg",
      "/img/portfolio/2021/skleyuvannya-trishchyn-tsehlyanykh-stin-20.jpg",
    ]
  },
  {
    "id": "vlashtuvannya-parkanu",
    "year": 2021,
    "title": "Влаштування паркану",
    "image": "/img/portfolio/cards/vlashtuvannya-parkanu-po-vul-otakara-yarosha.jpg",
    "place": "м.Харків, Україна",
    "technologies": ["Гідроізоляція", "Ремонт бетону та залізобетону", "Склеювання тріщин"],
    "body": "Влаштування паркану по вул. Отакара Яроша (м. Харків)",
    "descr": [
      ""
    ],
    "images": [
      "/img/portfolio/2021/vlashtuvannya-parkanu-1.jpg",
      "/img/portfolio/2021/vlashtuvannya-parkanu-2.jpg",
      "/img/portfolio/2021/vlashtuvannya-parkanu-3.jpg",
      "/img/portfolio/2021/vlashtuvannya-parkanu-4.jpg",
      "/img/portfolio/2021/vlashtuvannya-parkanu-5.jpg",
      "/img/portfolio/2021/vlashtuvannya-parkanu-6.jpg",
      "/img/portfolio/2021/vlashtuvannya-parkanu-7.jpg",
      "/img/portfolio/2021/vlashtuvannya-parkanu-8.jpg",
      "/img/portfolio/2021/vlashtuvannya-parkanu-9.jpg",
      "/img/portfolio/2021/vlashtuvannya-parkanu-10.jpg",
      "/img/portfolio/2021/vlashtuvannya-parkanu-11.jpg",
      "/img/portfolio/2021/vlashtuvannya-parkanu-12.jpg",
      "/img/portfolio/2021/vlashtuvannya-parkanu-13.jpg",
      "/img/portfolio/2021/vlashtuvannya-parkanu-14.jpg",
      "/img/portfolio/2021/vlashtuvannya-parkanu-15.jpg",
      "/img/portfolio/2021/vlashtuvannya-parkanu-16.jpg",
      "/img/portfolio/2021/vlashtuvannya-parkanu-17.jpg",
      "/img/portfolio/2021/vlashtuvannya-parkanu-18.jpg",
      "/img/portfolio/2021/vlashtuvannya-parkanu-19.jpg",
      "/img/portfolio/2021/vlashtuvannya-parkanu-20.jpg",
    ]
  }
]