export const slidertransparent = [
  '/img/technologies/page/promyslovi-ta-dekoratyvni-pidlohy/slider-transparent/prozori-propytky-dlya-betonnykh-pidloh-1.jpg',
  '/img/technologies/page/promyslovi-ta-dekoratyvni-pidlohy/slider-transparent/prozori-propytky-dlya-betonnykh-pidloh-2.jpg',
  '/img/technologies/page/promyslovi-ta-dekoratyvni-pidlohy/slider-transparent/prozori-propytky-dlya-betonnykh-pidloh-3.jpg',
  '/img/technologies/page/promyslovi-ta-dekoratyvni-pidlohy/slider-transparent/prozori-propytky-dlya-betonnykh-pidloh-4.jpg',
  '/img/technologies/page/promyslovi-ta-dekoratyvni-pidlohy/slider-transparent/prozori-propytky-dlya-betonnykh-pidloh-5.jpg',
  '/img/technologies/page/promyslovi-ta-dekoratyvni-pidlohy/slider-transparent/prozori-propytky-dlya-betonnykh-pidloh-6.jpg',
  '/img/technologies/page/promyslovi-ta-dekoratyvni-pidlohy/slider-transparent/prozori-propytky-dlya-betonnykh-pidloh-7.jpg',
  '/img/technologies/page/promyslovi-ta-dekoratyvni-pidlohy/slider-transparent/prozori-propytky-dlya-betonnykh-pidloh-8.jpg',
  '/img/technologies/page/promyslovi-ta-dekoratyvni-pidlohy/slider-transparent/prozori-propytky-dlya-betonnykh-pidloh-9.jpg',
  '/img/technologies/page/promyslovi-ta-dekoratyvni-pidlohy/slider-transparent/prozori-propytky-dlya-betonnykh-pidloh-10.jpg',
  '/img/technologies/page/promyslovi-ta-dekoratyvni-pidlohy/slider-transparent/prozori-propytky-dlya-betonnykh-pidloh-11.jpg',
  '/img/technologies/page/promyslovi-ta-dekoratyvni-pidlohy/slider-transparent/prozori-propytky-dlya-betonnykh-pidloh-12.jpg',
  '/img/technologies/page/promyslovi-ta-dekoratyvni-pidlohy/slider-transparent/prozori-propytky-dlya-betonnykh-pidloh-13.jpg',
  '/img/technologies/page/promyslovi-ta-dekoratyvni-pidlohy/slider-transparent/prozori-propytky-dlya-betonnykh-pidloh-14.jpg',
  '/img/technologies/page/promyslovi-ta-dekoratyvni-pidlohy/slider-transparent/prozori-propytky-dlya-betonnykh-pidloh-15.jpg',
]